import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";

import '../assets/bootstrap/css/bootstrap.min.css';
import '../assets/css/style.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HOME - AFFALXIMAM",
  description: "Generated by create next app",
};

export default function RootLayout({  children, }: Readonly <{  children: React.ReactNode; }> ) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
      </head>
      <body>
        {children}
        <Script src="/js/jquery-3.7.1.min.js"/>
        <Script src="/bootstrap/js/bootstrap.bundle.min.js"/>
        <Script src="/js/script.js" />
        </body>
    </html>
  );
}
